{
 "title": "Nightscout",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "id", "label": "dítě", "query": "CHLDREN_NAME" }
  ]
 },
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "pumpa baterie",
     "measurement": "testovaci",
     "select": [
      [
       { "params": [ "pbatery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "pumpa zásobník",
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"zasobnik\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "zasobnik" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "mobil baterie",
     "measurement": "testovaci",
     "select": [
      [
       { "params": [ "mbatery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Glykémie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "gl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"glykemie\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "delta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"delta\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "delta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Průměr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "gl",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"glykemie\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bg" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Sensitivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "/^$id$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sens" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "targetBG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "targetBG" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 18" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "dynISF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "basal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "select": [
      [
       { "params": [ "isf" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "IOB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "iob" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "COB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "basal",
     "measurement": "testovaci",
     "select": [
      [
       { "params": [ "cob" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "TBR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tbr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "základní bazál",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "basal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Glykémie",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Glykémie",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT last(\"bg\") FROM \"autogen\".\"testovaci\" WHERE (\"id\" =~ /^$id$/) AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "bg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Inzulín",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "IOB",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "iob" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "TBR",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"basal\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "tbr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "dynISF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ISF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"isf\" WHERE (\"id\" = 'lukin') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "isf" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "targetBG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "targetBG",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") *100 FROM \"sens\" WHERE (\"id\" = 'lukin') AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "targetBG" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 18" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Zásobník",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "zásobník",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"iob\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "zasobnik" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Baterie",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "pumpa",
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"pbatery\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pbatery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "mobil",
     "measurement": "testovaci",
     "query": "SELECT last(\"value\") FROM \"mbatery\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mbatery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "COB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "COB",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "testovaci",
     "query": "SELECT mean(\"value\") FROM \"cob\" WHERE (\"id\" =~ /^$id$/) AND $timeFilter GROUP BY time($__interval), \"/^$id$/\" fill(none)",
     "select": [
      [
       { "params": [ "cob" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  }
 ]
}